name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install pandoc
          uv sync

      - name: Lint with ruff
        run: |
          uv run ruff compotime tests

      - name: Test with pytest
        run: |
          uv run make tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build documentation
        run: |
          uv run make docs

      - name: Check compatibility with other libraries
        run: |
          uv add statsmodels scikit-learn
