name: Build Python distribution and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.9"
      - name: Build
        run: |
          uv build
      - name: Publish distribution to PyPI
        run: |
          uv publish --token ${{ secrets.PYPI_TOKEN }}
